name: 'BundleStats'
description: 'Generates bundle-stats reports for webpack stats.'
branding:
  icon: 'box'
  color: 'blue'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  id: 
    description: 'Run id'
    required: false,
  webpack-stats-path:
    description: 'Webpack stats filepath'
    required: true
    default: 'dist/webpack-stats.json'
  repo-token: 
    description: 'Github action auth token'
    required: false
    default: ''
